#服务器配置
server:
  port: 9848
  session:

  servlet:
    session:
      timeout: 10

#传输配置
http:
  encoding:
    charset: utf-8
    enable: true

#数据库配置、驱动、JPA
spring:
  datasource:
    #黄广祥
#    url: jdbc:mysql://127.0.0.1:3306/cloud_house_management?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
#    username: root
#    password: 123456

    #pro
    url: jdbc:mysql://rm-wz9r1o3f8f4m9qbv8ko.mysql.rds.aliyuncs.com:3306/cloud_house?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: Rbi@2019@Red

    #test
    #    url: jdbc:mysql://192.168.28.152:3306/cloud_house?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
    #    username: root
    #    password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver（6.0版本以上）
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    #设置innerDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect



    #Redis配置
  redis:
    host: 127.0.0.1
    password:
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait:
        min-idle: 0
    timeout: 0


  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true