spring:
  resources:
    static-locations: classpath:/META-INF/resources,classpath:/resources,classpath:/static
  mvc:



    static-path-pattern: /**
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML5
  datasource:
    url: jdbc:mysql://rm-wz9r1o3f8f4m9qbv8ko.mysql.rds.aliyuncs.com:3306/cloud_house?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
    username: root
    password: Rbi@2019@Red
    dbcp2:
      max-idle: 10
      min-idle: 5
      initial-size: 5
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    database: 0
    host: 139.9.225.98
    lettuce:
      shutdown-timeout: 2000
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 30
        max-wait: 10000
        max-idle: 30
        min-idle: 10
    password: rbi2018@


server:
  port: 80
  servlet:
    session:
      timeout: 10m
    context-path: /
  tomcat:
    uri-encoding: UTF-8
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
pagehelper:
 helperDialect: mysql
 reasonable: true
 supportMethodsArguments: true
 params: count=countSq

dubbo:
  application:
    name: wx
  registry:
    protocol: zookeeper
    address: 120.77.171.73:2181
  protocol:
    name: dubbo
    port: 20884
  consumer:
    check: false
